metadata:
  favicon: ''
  code: |-
    <style>
      ub-horizontal-menu a[nbButton].active, ub-horizontal-menu a[nbButton]:hover {
        background-color: rgb(69 112 246 / 37%)!important;
      }
      
      .no-shadow button {
        filter: none!important;
      }
    </style>
  title: New app
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
internalType: project
